### ISSUE TITLE
Add `repository` and `homepage` info to `package.json`

### ISSUE THREAD

**Issue by andrejpavlovic** [h-sphere/omnibus#11]
When I originally found this library on npmjs it took me quite a while to find the git repository, since it's not linked directly. Adding `repository` and/or `homepage` info to `package.json` that link to this repo would make it easier to find!

Great library by the way, and I'm looking forward to trying out the latest updates!

**Comment by kulak-at** [comment]
Thank you for the suggestion and kind words! I've just released a new version with an updated `package.json`.
